### GET request
GET http://localhost:8080/v1/service/a/k
Accept: application/json
Content-Type: application/json

###

## POST request
POST http://localhost:8080/v1/service
Accept: application/json
Content-Type: application/json

{
  "param1": "param1",
  "param2": "param2"
}
